add shadow and index text to points and fit to screen
Trendyol/android-ui-components pull request #116
Opened 2023-07-21 10:48 UTC by edaersu

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-07-23 15:51 UTC, bsobe requested changes

2023-07-23 15:51 UTC, bsobe commented on libraries/timeline-view-compose/README.md
> +###### PointShadowConfig
may you recheck these lines

2023-07-23 15:51 UTC, bsobe commented on libraries/timeline-view-compose/src/main/java/com/trendyol/uicomponents/timelineviewcompose/HorizontalTimelineWithIndexTextView.kt
> +            HorizontalTimelineWithIndexTextItemItem(
is the name of the function is correct?

2023-07-27 07:05 UTC, erolaksoy approved these changes

2023-07-27 07:06 UTC, merged